server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
